
cubo = {
    "entero": {
      "entero": {
        "+":"entero", 
        "-":"entero", 
        "*":"entero", 
        "/":"entero", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"entero",
        "==": "bool", 
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        }, 
      "real": {
        "+":"real", 
        "-":"real", 
        "*":"real", 
        "/":"real", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"entero", 
        "==": "bool",
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        },  
      "char": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      }, 
    "real":{
      "entero": {
        "+":"real", 
        "-":"real", 
        "*":"real", 
        "/":"real", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"real",
        "==": "bool", 
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        }, 
      "real": {
        "+":"real", 
        "-":"real", 
        "*":"real", 
        "/":"real", 
        ">":"bool", 
        ">=":"bool",
        "<=":"bool",
        "<":"bool", 
        "=":"real", 
        "==": "bool",
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        },  
      "char": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error",
        "==": "Error", 
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error",
        "==": "Error", 
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      }, 
    "char":{
      "entero": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "real": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },  
      "char": {
        "+":"char", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"char", 
        "==": "bool",
        "!=":"bool",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      }, 
    "bool":{
      "entero": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "real": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "char": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"bool", 
        "==":"bool",
        "!=":"bool",
        "and":"bool", 
        "or":"bool",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      },
    "List":{
      "entero": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "real": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },  
      "char": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"bool",
        "<=":"bool",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error",
        ">=":"Error",
        "<=":"Error", 
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      },
    "Array":{
      "entero": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "real": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },  
      "char": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        }, 
      "bool": {
        "+":"Error", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==":"Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      "Array": {
        "+":"Array", 
        "-":"Error", 
        "*":"Error", 
        "/":"Error", 
        ">":"Error", 
        ">=":"Error",
        "<=":"Error",
        "<":"Error", 
        "=":"Error", 
        "==": "Error",
        "!=":"Error",
        "and":"Error", 
        "or":"Error",
        },
      },
    }