# tab.py. This file automatically created by PLY (version 3.8). Don't edit!
_tabversion   = '3.8'
_lextokens    = {'MAS', 'AND', 'MENORQUE', 'ENTONCES', 'IGUALPOR', 'IGUALIGUAL', 'IGUALMENOS', 'MIENTRAS', 'MENOS', 'TYPEID', 'ICONST', 'PARIZQ', 'CCONST', 'REGRESA', 'MODULO', 'PUNTOCOMA', 'ENTERO', 'PARDER', 'COMA', 'HASTA', 'PRINCIPAL', 'SI', 'REAL', 'ESCRIBE', 'LLAVEIZQ', 'REPITE', 'IGUAL', 'SINO', 'BOOL', 'DIV', 'HAZ', 'CHAR', 'DIFERENTE', 'MOD', 'ANDBIT', 'DOBLEPORCENTAJE', 'IGUALDIV', 'CONDOP', 'CORIZQ', 'COMILLAS', 'SCONST', 'MULTI', 'IGUALMOD', 'IGUALMAS', 'MASMAS', 'VOID', 'LLAVEDER', 'MAYORQUE', 'ELLIPSIS', 'PUNTO', 'OR', 'LEE', 'MAYORIGUAL', 'GATO', 'PROGRAMA', 'NOT', 'FCONST', 'MENOSMENOS', 'DOSPUNTOS', 'MENORIGUAL', 'ID', 'CORDER'}
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NEWLINE>\\n+)|(?P<t_ID>[a-zA-Z_][a-zA-Z0-9_]*)|(?P<t_CHAR>"(\\\\.|[^\\\\"])*\\")|(?P<t_REAL>[0-9]+\\.[0-9]+)|(?P<t_ENTERO>[0-9]+)|(?P<t_comment> %%(.|\\n)*?%%)|(?P<t_ELLIPSIS>\\.\\.\\.)|(?P<t_OR>\\|\\|)|(?P<t_MASMAS>\\+\\+)|(?P<t_IGUALMAS>\\+=)|(?P<t_IGUALPOR>\\*=)|(?P<t_DIFERENTE>!=)|(?P<t_AND>&&)|(?P<t_LLAVEDER>\\{)|(?P<t_IGUALMOD>%=)|(?P<t_MENORIGUAL>>=)|(?P<t_PARIZQ>\\()|(?P<t_LLAVEIZQ>\\})|(?P<t_CONDOP>\\?)|(?P<t_CORDER>\\[)|(?P<t_GATO>\\#)|(?P<t_IGUALIGUAL>==)|(?P<t_MAS>\\+)|(?P<t_IGUALDIV>/=)|(?P<t_PARDER>\\))|(?P<t_PUNTO>\\.)|(?P<t_MULTI>\\*)|(?P<t_MAYORIGUAL><=)|(?P<t_CORIZQ>\\])|(?P<t_MENOSMENOS>--)|(?P<t_IGUALMENOS>-=)|(?P<t_DOSPUNTOS>:)|(?P<t_ANDBIT>&)|(?P<t_MAYORQUE><)|(?P<t_MENOS>-)|(?P<t_NOT>!)|(?P<t_MENORQUE>>)|(?P<t_DIV>/)|(?P<t_IGUAL>=)|(?P<t_COMA>,)|(?P<t_COMILLAS>")|(?P<t_PUNTOCOMA>;)|(?P<t_MOD>%)', [None, ('t_NEWLINE', 'NEWLINE'), ('t_ID', 'ID'), ('t_CHAR', 'CHAR'), None, ('t_REAL', 'REAL'), ('t_ENTERO', 'ENTERO'), ('t_comment', 'comment'), None, (None, 'ELLIPSIS'), (None, 'OR'), (None, 'MASMAS'), (None, 'IGUALMAS'), (None, 'IGUALPOR'), (None, 'DIFERENTE'), (None, 'AND'), (None, 'LLAVEDER'), (None, 'IGUALMOD'), (None, 'MENORIGUAL'), (None, 'PARIZQ'), (None, 'LLAVEIZQ'), (None, 'CONDOP'), (None, 'CORDER'), (None, 'GATO'), (None, 'IGUALIGUAL'), (None, 'MAS'), (None, 'IGUALDIV'), (None, 'PARDER'), (None, 'PUNTO'), (None, 'MULTI'), (None, 'MAYORIGUAL'), (None, 'CORIZQ'), (None, 'MENOSMENOS'), (None, 'IGUALMENOS'), (None, 'DOSPUNTOS'), (None, 'ANDBIT'), (None, 'MAYORQUE'), (None, 'MENOS'), (None, 'NOT'), (None, 'MENORQUE'), (None, 'DIV'), (None, 'IGUAL'), (None, 'COMA'), (None, 'COMILLAS'), (None, 'PUNTOCOMA'), (None, 'MOD')])]}
_lexstateignore = {'INITIAL': ' \t\x0c'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
