# tab.py. This file automatically created by PLY (version 3.8). Don't edit!
_tabversion   = '3.8'
_lextokens    = {'PRINCIPAL', 'DOSPUNTOS', 'MODULO', 'SINO', 'HASTA', 'VOID', 'ENTERO', 'DIV', 'COMA', 'OR', 'MIENTRAS', 'PARIZQ', 'MAYORIGUAL', 'LEER', 'MAS', 'MENORIGUAL', 'SI', 'COMILLAS', 'PESOS', 'REGRESA', 'CORDER', 'MENOS', 'NOT', 'INTERROGACION', 'PARDER', 'ANDBIT', 'ESCRIBIR', 'DOBLEPORCENTAJE', 'MULTI', 'MOD', 'PROGRAMA', 'CHAR', 'REAL', 'HAZ', 'REPITE', 'ENTONCES', 'IGUAL', 'MENOSMENOS', 'AND', 'LLAVEIZQ', 'ID', 'BOOL', 'PUNTOCOMA', 'MASMAS', 'LLAVEDER', 'IGUALIGUAL', 'CORIZQ', 'MENORQUE', 'MAYORQUE', 'DIFERENTE', 'PUNTO'}
_lexreflags   = 0
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_NEWLINE>\\n+)|(?P<t_comment> %%(.|\\n)*?%%)|(?P<t_ID>[a-zA-Z_][a-zA-Z0-9_]*)|(?P<t_CHAR>"(\\\\.|[^\\\\"])*\\")|(?P<t_REAL>[0-9]+\\.[0-9]+)|(?P<t_ENTERO>[0-9]+)|(?P<t_MASMAS>\\+\\+)|(?P<t_OR>\\|\\|)|(?P<t_IGUALIGUAL>==)|(?P<t_LLAVEDER>\\})|(?P<t_LLAVEIZQ>\\{)|(?P<t_PARDER>\\))|(?P<t_CORIZQ>\\[)|(?P<t_MAS>\\+)|(?P<t_PESOS>\\$)|(?P<t_MULTI>\\*)|(?P<t_PUNTO>\\.)|(?P<t_CORDER>\\])|(?P<t_MENOSMENOS>--)|(?P<t_AND>&&)|(?P<t_DIFERENTE>!=)|(?P<t_PARIZQ>\\()|(?P<t_MAYORIGUAL><=)|(?P<t_INTERROGACION>\\?)|(?P<t_MENORIGUAL>>=)|(?P<t_IGUAL>=)|(?P<t_ANDBIT>&)|(?P<t_DIV>/)|(?P<t_PUNTOCOMA>;)|(?P<t_COMILLAS>")|(?P<t_MOD>%)|(?P<t_MENOS>-)|(?P<t_MENORQUE>>)|(?P<t_DOSPUNTOS>:)|(?P<t_NOT>!)|(?P<t_COMA>,)|(?P<t_MAYORQUE><)', [None, ('t_NEWLINE', 'NEWLINE'), ('t_comment', 'comment'), None, ('t_ID', 'ID'), ('t_CHAR', 'CHAR'), None, ('t_REAL', 'REAL'), ('t_ENTERO', 'ENTERO'), (None, 'MASMAS'), (None, 'OR'), (None, 'IGUALIGUAL'), (None, 'LLAVEDER'), (None, 'LLAVEIZQ'), (None, 'PARDER'), (None, 'CORIZQ'), (None, 'MAS'), (None, 'PESOS'), (None, 'MULTI'), (None, 'PUNTO'), (None, 'CORDER'), (None, 'MENOSMENOS'), (None, 'AND'), (None, 'DIFERENTE'), (None, 'PARIZQ'), (None, 'MAYORIGUAL'), (None, 'INTERROGACION'), (None, 'MENORIGUAL'), (None, 'IGUAL'), (None, 'ANDBIT'), (None, 'DIV'), (None, 'PUNTOCOMA'), (None, 'COMILLAS'), (None, 'MOD'), (None, 'MENOS'), (None, 'MENORQUE'), (None, 'DOSPUNTOS'), (None, 'NOT'), (None, 'COMA'), (None, 'MAYORQUE')])]}
_lexstateignore = {'INITIAL': ' \t\x0c'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
